### ISSUE TITLE
Publish the docker container to docker hub

### ISSUE THREAD

**Issue by szaimen** [strukturag/pdfdraw#17]
Hey,

I wonder if you could publish the docker container to docker hub?
Would be great!

Greetings, szaimen

**Comment by fancycode** [comment]
The container will be available at https://hub.docker.com/r/strukturag/pdfdraw and https://github.com/strukturag/pdfdraw/pkgs/container/pdfdraw.

A new version is built on each commit and for tagged releases.

**Comment by szaimen** [comment]
Thanks! sounds good!
