### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sunjam** [strukturag/pdfdraw#22]
Related to #21 PHP 8 support was introduced.  7.x will continue to be supported for the time being.

**Comment by fancycode** [comment]
Are there any issues with running with PHP8?

**Comment by sunjam** [comment]
I'm unsure for this app. Might be fine. I'm still on 7.4

Hope this is helpful

**Comment by fancycode** [comment]
Feel free to reopen if you encounter actual problems when running with PHP 8.
