### ISSUE TITLE
404 retrieving original pdf from nextcloud

### ISSUE THREAD

**Issue by lbdroid** [strukturag/pdfdraw#29]
When combining pdf files, it generates a request to the nextcloud server for the original PDF file, which nextcloud cannot process.

https://github.com/strukturag/pdfdraw/blob/master/server/server.js#L396

my.ip - - [03/Apr/2021:16:15:50 -0400] "GET /apps/pdfdraw/download/483340 HTTP/1.1" 404 7371878 "-" "-"

**Comment by lbdroid** [comment]
Changing 200 into 404 on this line makes it work;
https://github.com/strukturag/pdfdraw/blob/master/server/server.js#L414

**Comment by fancycode** [comment]
Was this a file on external storage / group folders? If so, this should be fixed with #57

**Comment by fancycode** [comment]
Please reopen with more details on the storage of the file if this still happens with latest master.
