### ISSUE TITLE
Reimplement server in php and/or eliminate backend

### ISSUE THREAD

**Issue by lbdroid** [strukturag/pdfdraw#30]
It would be much preferred to have the backend implemented in PHP, since that would permit the webserver to handle the backend directly instead of proxying it to an unnecessary additional server. There isn't anything in server.js that wouldn't be easy to rewrite in php.

In addition, having it rewritten in php may allow the backend to be eliminated altogether -- just fold it into the frontend.

**Comment by fancycode** [comment]
The server.js is providing a websocket endpoint for realtime changes of the annotations so multiple people can work concurrently on the same document. This is hardly possible inside Nextcloud with PHP and is not planned to be changed.
