### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by lbdroid** [strukturag/pdfdraw#33]
I'm not making a pull request because it isn't ready for that just yet, but I figured that the changes I've made would probably be useful for someone.

https://github.com/lbdroid/pdfdraw/commit/76e7eb0663f527dd041769c34fe3ecc18d81d174

This implements save-in-place, fixes the problem with nextcloud responding with error 404, and partially fixes work within group folders (create a user named "testuser" and grant access to the group data for now).

When you hit the save button, it saves in place, it does NOT download -- currently sticks you with an error, but that's related to the download not the save.

**Comment by fancycode** [comment]
When saving inplace, there is no way to change / remove annotations later. While this a nice optional feature, it is currently not in the scope of pdfdraw.
