### ISSUE TITLE
"Connecting to server please wait"

### ISSUE THREAD

**Issue by elhananjair** [strukturag/pdfdraw#34]
Hello there I have installed pdfdraw using docker, and I was trying to use it. Now after I started the container and opened one pdf file with "annotate" option, it says "connecting to server please wait" and do nothing. Here is the log...

> {"reqId":"YHa7hmOPGXBL5rLfsUohFwAABAw","level":3,"time":"2021-04-14T09:53:10+00:00","remoteAddr":"192.168.15.17","user":"Amanuel Kumera","app":"PHP","method":"GET","url":"/apps/pdfdraw/viewer/5649?file=https://nextacso.com/apps/pdfdraw/d/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvbmV4dGFjc28uY29tIiwic3ViIjoiQW1hbnVlbCBLdW1lcmEiLCJleHAiOjE2MTgzOTQyOTAsImZpbGVJZCI6IjU2NDkiLCJ0b2tlbiI6bnVsbH0.EAoLuLOQX5_y5hjgVVFKuTDZaKYzkO_RDTa_8b5SEW4","message":{"Exception":"Error","Message":"Undefined index: scheme at /var/www/html/nextcloud/apps/pdfdraw/lib/Controller/ViewerController.php#398","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/pdfdraw/lib/Controller/ViewerController.php","line":398,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"viewer","class":"OCA\\Pdfdraw\\Controller\\ViewerController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.76","version":"21.0.1.1","id":"6076d6b165f09"}

**Comment by lbdroid** [comment]
Did you configure nextcloud and the backend to communicate with each other?
What requests and response codes are actually being logged by your web server?
What is the output of your backend when you try to connect?

Note that this project is structured horribly. The backend shouldn't actually exist at all -- it doesn't do anything useful and just makes things complicated and difficult to configure.

Good luck.

**Comment by lbdroid** [comment]
Also, try changing https://github.com/strukturag/pdfdraw/blob/master/lib/Controller/ViewerController.php#L294

```'/apps/pdfdraw/viewer/'``` to ```'/index.php/apps/pdfdraw/viewer/'```

**Comment by elhananjair** [comment]
As you mentioned on another issue section, I will wait for better structured form of this app, the idea is great by itself. Thanks for your effort.

**Comment by lbdroid** [comment]
Try this; https://gitlab.com/nextcloud-other/nextcloud-annotate

**Comment by elhananjair** [comment]
Okay I will thanks

**Comment by lbdroid** [comment]
I cleaned up a few of the rough edges on it.
- handles rotated pdf's correctly now,
- the save button now says "save",
- user feedback when saving,
- works better on small screens (i.e. tablets).
