### ISSUE TITLE
Fundamentally bad design

### ISSUE THREAD

**Issue by lbdroid** [strukturag/pdfdraw#35]
I've decided that this project is basically abandoned, and I'm starting to work on a (currently private) fork.

The initial objective will be to eliminate the unnecessary backend server, which is actually pretty easy. I've already got the whole input side of it working without any kind of backend connection at all, and dumping what data would be sent to the backend out to the javascript console. This annotation data will be stored locally (client's browser) until they decide to do something with it -- mainly to save an annotated PDF to nextcloud. I don't see a particular urgency to store annotations in the database for later, but it could be addressed.

A bunch of this program revolves around the notion of real-time multi-user annotations. I do NOT see this as an important feature at all, and I'm sure most others would agree, so I'm not going to waste any time with that kind of nonsense, however, I will document my thoughts on implementing such a feature should anyone wish to do so; in particular, rather than saving the changes through the backend/websocket, feed it to nextcloud using XHR and using the notification subsystem to trigger data retrievals on other clients.

Once I've got the basic functionality working again without the backend, I'll work on adding text and customizable stamps.

**Comment by lbdroid** [comment]
I'm finding it disgusting just how close the code here is to being useful without their having taken that last step of actually binding it together properly. The "downloadPdf" function (browser javascript) creates an array of SVG's (one for each page in the PDF), POST's it to the backend, which converts the SVG's to PDF, obtains the original PDF from nextcloud, layers them together, and feeds it back to the client. The backend doesn't even use special functionality to process the data, it just calls executables on the host, so there's absolutely no reason it should post the data to the backend instead of to nextcloud.

**Comment by lbdroid** [comment]
Huh, I'm already sending the SVG data directly to nextcloud using an authenticated endpoint. Now really all that's left to do is mechanical processing of the SVG and PDF, and a heap of cleanups and repackaging.

**Comment by lbdroid** [comment]
That was pretty easy to fix; https://gitlab.com/nextcloud-other/nextcloud-annotate
This does everything that "pdfdraw" does, actually saves properly back to Nextcloud, gets rid of the nasty "backend", and fixes and simplifies a whole lot.

**Comment by fancycode** [comment]
Feel free to fork this project if you want to use it for something else.

However make sure to keep the license information of files you copied (AGPL). From a quick look in your repository you reused lots of the code from pdfdraw but removed all the license information.
