### ISSUE TITLE
Uncaught ReferenceError: pdfjsLib is not defined

### ISSUE THREAD

**Issue by zhaotao1989** [strukturag/pdfdraw#4]
I found the following two files is the best choice?

https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.min.js
https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.worker.min.js

**Comment by fancycode** [comment]
Did you run `make` after checking out the repository? This will download a version of pdfjs that is used by the app.

**Comment by zhaotao1989** [comment]
I downloaded the release package directly and did not check out the source code.

I read the Makefile and found "--exclude = build" is included in the appstore build command. Is pdfjs missing from the release package because of this?

![image](https://user-images.githubusercontent.com/7676211/101970672-b96a1500-3c66-11eb-84c0-1ef94d354635.png)

**Comment by fancycode** [comment]
Sorry, the files were indeed missing from the last release tarball. Fixed with the just released 0.1.2.

**Comment by Superstar-dev1** [comment]
> I found the following two files is the best choice?
> 
> https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.min.js https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.worker.min.js

I used them but I met this bug.
"Uncaught ReferenceError: pdfjsLib is not defined"
There is no pdfjsLib in those files.

But there is pdfjsLIB in this file. 
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js
